version: '3'

services:
    rundeck:
        image: rundeck/rundeck:SNAPSHOT
        links:
          - mysql
        environment:
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
            RUNDECK_GRAILS_URL: localhost:4440
            RUNDECK_GRAILS_URL: https://RUNDECKURL
            RUNDECK_SERVER_ADDRESS: 0.0.0.0
            RUNDECK_SERVER_FORWARDED: 'true'
        volumes:
          - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
        ports:
          - 4440:4440
    mysql:
        image: mysql:5.7
        expose:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
        volumes:
          - ./dbdata:/var/lib/mysql
    nginx-ssl:
        container_name: rundeck-ssl
        image: tumsqual/nginx-ssl:latest
        restart: always
        depends_on:
          - rundeck
        ports:
          - 80:80
          - 443:443
        volumes:
          - /opt/rundeck-docker/nginx-config:/etc/nginx/conf.d
          - /opt/rundeck-docker/nginx-ssl:/etc/nginx/certs
          - /var/run/docker.sock:/tmp/docker.sock:ro
